# Generated by Django 3.2 on 2022-06-04 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0011_auto_20220604_1420'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='editor',
        ),
        migrations.RenameField(
            model_name='follow',
            old_name='user',
            new_name='editor',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='user',
            new_name='editor',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='editor',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='editor',
        ),
    ]
