# Generated by Django 3.2 on 2022-06-04 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0013_alter_profile_profile_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comments',
        ),
    ]
