# Generated by Django 3.2 on 2022-06-05 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0014_remove_post_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.AlterField(
            model_name='comment',
            name='editor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insta.profile'),
        ),
        migrations.AlterField(
            model_name='like',
            name='editor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insta.profile'),
        ),
        migrations.AlterField(
            model_name='post',
            name='editor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insta.profile'),
        ),
    ]
