# Generated by Django 3.2 on 2022-06-06 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0015_auto_20220605_1543'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='editor',
            new_name='follower',
        ),
        migrations.RenameField(
            model_name='follow',
            old_name='profile',
            new_name='following',
        ),
    ]
